Include dll file information into warp package

diff --git a/.github/workflows/tagged_release.yml b/.github/workflows/tagged_release.yml
--- a/.github/workflows/tagged_release.yml
+++ b/.github/workflows/tagged_release.yml
@@ -142,6 +142,23 @@ jobs:
           mv "./$bundle/jdk-25.0.3+9-jre" "./$bundle/jre"
           rm jre.zip
 
+          cp "./$bundle/jre/bin/jli.dll" "./$bundle/app/"
+          cp "./$bundle/jre/bin/server/jvm.dll" "./$bundle/app/"
+          
+          m2_repo="${USERPROFILE//\\//}/.m2/repository"
+
+          zstd_jar=$(find "$m2_repo" -name "zstd-jni-*.jar" ! -name "*-sources.jar" ! -name "*-javadoc.jar" | head -n 1)
+          
+          if [ -n "$zstd_jar" ] && [ -f "$zstd_jar" ]; then
+              cp "$zstd_jar" "./$bundle/app/"
+          else
+              echo "Error: zstd-jni JAR not found in $m2_repo!"
+              exit 1
+          fi
+          
+          echo "Bundle app folder:"
+          ls -l "./$bundle/app/"
+
           mv aspect-model-editor-runtime/target/aspect-model-editor-runtime-${{ env.RELEASE_VERSION }}.jar "./$bundle/app"
           
           GOOS=windows GOARCH=amd64 go build -ldflags -H=windowsgui -o "./$bundle/run.exe" scripts/windows/run.go
